ALTER TABLE T50FILES.VEBSESS ADD  COLUMN  PUNCHOUT_POST_URL      FOR ELPPURL VARCHAR(512) NOT NULL DEFAULT ''
GO
ALTER TABLE T50FILES.VEBSESS ADD  COLUMN  PUNCHOUT_NET_ID        FOR ELPNETID VARCHAR(30) NOT NULL DEFAULT ''
GO
ALTER TABLE T50FILES.VEBSESS ADD  COLUMN  PUNCHOUT_ADDR_ID       FOR ELPADDID VARCHAR(10) NOT NULL DEFAULT ''
GO
ALTER TABLE T50FILES.VEBSESS ADD  COLUMN  PUNCHOUT_BUYER_COOKIE  FOR ELPCOOK VARCHAR(100) NOT NULL DEFAULT ''
GO

CREATE TABLE T50FILES.VEBPUNXREF  ( 
	B1DEL  	CHARACTER(1) NOT NULL DEFAULT '',
	B1CMP  	NUMERIC(3,0) NOT NULL DEFAULT 0,
	B1NETID	CHARACTER(25) NOT NULL DEFAULT '',
	B1ADDID	CHARACTER(10) NOT NULL DEFAULT '',
	B1CUST 	CHARACTER(7) NOT NULL DEFAULT '',
	B1SHIP 	CHARACTER(7) NOT NULL DEFAULT '',
	B1USER 	CHARACTER(30) 
	)
GO
LABEL ON TABLE T50FILES.VEBPUNXREF IS 'Customer/Shipto cross ref for Punchout'
GO
LABEL ON COLUMN T50FILES.VEBPUNXREF.B1DEL IS 'Status'
GO
LABEL ON COLUMN T50FILES.VEBPUNXREF.B1CMP IS 'Company'
GO
LABEL ON COLUMN T50FILES.VEBPUNXREF.B1NETID IS 'Network Id'
GO
LABEL ON COLUMN T50FILES.VEBPUNXREF.B1ADDID IS 'Address Id'
GO
LABEL ON COLUMN T50FILES.VEBPUNXREF.B1CUST IS 'Customer'
GO
LABEL ON COLUMN T50FILES.VEBPUNXREF.B1SHIP IS 'Shipto'
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON T50FILES.VEBPUNXREF TO PUBLIC
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, INDEX, REFERENCES ON T50FILES.VEBPUNXREF TO VAIGROUP WITH GRANT OPTION
GO
GRANT UPDATE(B1USER), REFERENCES(B1USER) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(B1SHIP), REFERENCES(B1SHIP) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(B1NETID), REFERENCES(B1NETID) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(B1DEL), REFERENCES(B1DEL) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(B1CUST), REFERENCES(B1CUST) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(B1CMP), REFERENCES(B1CMP) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(B1ADDID), REFERENCES(B1ADDID) ON T50FILES.VEBPUNXREF TO PUBLIC WITH GRANT OPTION
GO

CREATE TABLE T50FILES.VEBPUNCH  ( 
	PSESSION	CHARACTER(30) NOT NULL DEFAULT '',
	WEBUSER 	CHARACTER(30) NOT NULL DEFAULT '',
	WDATE   	NUMERIC(8,0) NOT NULL DEFAULT 0,
	WTIME   	NUMERIC(6,0) NOT NULL DEFAULT 0,
	WBCOOKIE	CHARACTER(80) NOT NULL DEFAULT '',
	WPURL   	VARCHAR(512) NOT NULL DEFAULT '' 
	)
GO
LABEL ON TABLE T50FILES.VEBPUNCH IS 'Session Master List for Punchout'
GO
LABEL ON COLUMN T50FILES.VEBPUNCH.PSESSION IS 'Session Id'
GO
LABEL ON COLUMN T50FILES.VEBPUNCH.WEBUSER IS 'User Id'
GO
LABEL ON COLUMN T50FILES.VEBPUNCH.WDATE IS 'Session Start Date'
GO
LABEL ON COLUMN T50FILES.VEBPUNCH.WTIME IS 'Session Start Time'
GO
LABEL ON COLUMN T50FILES.VEBPUNCH.WBCOOKIE IS 'Cookie Id'
GO
LABEL ON COLUMN T50FILES.VEBPUNCH.WPURL IS 'Session URL'
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON T50FILES.VEBPUNCH TO PUBLIC
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, INDEX, REFERENCES ON T50FILES.VEBPUNCH TO VAIGROUP WITH GRANT OPTION
GO
GRANT UPDATE(WTIME), REFERENCES(WTIME) ON T50FILES.VEBPUNCH TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(WPURL), REFERENCES(WPURL) ON T50FILES.VEBPUNCH TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(WEBUSER), REFERENCES(WEBUSER) ON T50FILES.VEBPUNCH TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(WDATE), REFERENCES(WDATE) ON T50FILES.VEBPUNCH TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(WBCOOKIE), REFERENCES(WBCOOKIE) ON T50FILES.VEBPUNCH TO PUBLIC WITH GRANT OPTION
GO
GRANT UPDATE(PSESSION), REFERENCES(PSESSION) ON T50FILES.VEBPUNCH TO PUBLIC WITH GRANT OPTION
GO